name: Shuttle deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          allow-dirty: true
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
